### ISSUE TITLE
linux-multi - No such file or directory (os error 2)

### ISSUE THREAD

**Issue by ixxie** [DeterminateSystems/nix-installer#1012]
Running on Ubuntu 24.04 LTS

1. I previously used determinate installer to set up a single-user install succesfully
2. The install didn't work for root users, so I then used the determinate installer to uninstall nix. 
3. Now I attempted to reinstall with a multi-user setup with `nix-installer install linux-multi` as explained in the README

In addition to the autogenerated error below, I got the following:
```
Location:
   src/cli/subcommand/install.rs:152

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.
```

# Autogenerated:

## Error
```
Error: 
   0: Reading plan
   1: No such file or directory (os error 2)
```

## Metadata
|key|value|
|--|--|
|**version**|0.19.0|
|**os**|linux|
|**arch**|x86_64|

**Comment by cole-h** [comment]
Oops, looks like that `multi-user` mention was a documentation bug that was fixed in https://github.com/DeterminateSystems/nix-installer/commit/6b183fcaea9545a64c558af821ec43e5251a683a. We install multi-user by default, so you should be able to install by just running `nix-installer install` without anything else.
