### ISSUE TITLE
can't use flakes even if nix.conf is updated

### ISSUE THREAD

**Issue by deekshith991** [DeterminateSystems/nix-installer#1052]

**Comment by cole-h** [comment]
Could you please provide some more info?

* What installer version did you use?
* What version of Nix are you running?
* What happens when you try to use something that requires the `flakes` feature? (Screenshots or terminal text output would be helpful.)
* What are the contents of `/etc/nix/nix.conf` and `~/.config/nix/nix.conf`?
* Does it start working if you restart the Nix daemon (`systemctl restart nix-daemon` on Linux, `launchctl bootout system org.nixos.nix-daemon && launchctl bootstrap system org.nixos.nix-daemon` on macOS, I think)?

**Comment by a-h** [comment]
I was troubleshooting this with someone today, they were getting messages about setting `experimental-features = nix-command flakes` etc.

@cole-h's post was useful for me, because I looked at the `~/.config/nix/nix.conf` and noticed that it set experimental-features, and that those overrode the ones in `/ext/nix/nix.conf`, so for me deleting `~/.config/nix/nix.conf` did the trick.

**Comment by cole-h** [comment]
I'm going to close this now, feel free to reopen if you run into the issue again and/or can provide more details!
