### ISSUE TITLE
error reinstalling nix on mac os after restoring a mac backup

### ISSUE THREAD

**Issue by niczem** [DeterminateSystems/nix-installer#1056]
I used your awesome installer on my old machine which was damaged. after restoring a time machine backup nix was not installed anymore. When trying to reinstall it with your installer i get the following error:

## Error
```
Error: 
   0: Install failure
   1: Error executing action
   2: Action `configure_init_service` errored
   3: Failed to execute command with status 5 `"launchctl" "bootstrap" "system" "/Library/LaunchDaemons/org.nixos.nix-daemon.plist"`, stdout: 
      stderr: Bootstrap failed: 5: Input/output error


```

## Metadata
|key|value|
|--|--|
|**version**|0.20.1|
|**os**|macos|
|**arch**|aarch64|
 Installation failure, offering to revert...

**Comment by cole-h** [comment]
What happens if you rerun the installer...? I think we've seen some "temporary" issues when `launchctl bootstrap`ing the daemon that we believe will work if it's rerun...

If it fails again, don't let revert uninstall anything, run the command manually a few times to see if it succeeds, and if it does, rerun the installer and hopefully it'll pick up where it left off.

If it doesn't work even after running that command manually a few times, that would also be useful information to know!

**Comment by zaynetro** [comment]
Happened to me as well. Rollbacked the installation and ran installer again. Things worked on the second try.
