### ISSUE TITLE
Failed to execute command `"mount" "-d"`: No such file or directory (os error 2)

### ISSUE THREAD

**Issue by yatesco** [DeterminateSystems/nix-installer#1160]
## Error
```
Error: 
   0: Planner error
   1: Error executing action
   2: Action `configure_nix` errored
   3: Action `place_nix_configuration` errored
   4: Action `create_directory` errored
   5: Failed to execute command `"mount" "-d"`
   6: No such file or directory (os error 2)
```

## Metadata
|key|value|
|--|--|
|**version**|0.25.0|
|**os**|macos|
|**arch**|x86_64|

**Comment by szethh** [comment]
hi! i'm running into this, but while uninstalling. i can't use these changes since whenever i try to curl the installer, it errors out and tells me to run `/nix/nix-installer uninstall` instead...

i'm trying to get a clean nix installation, since upgrading it borked my nix install (couldn't connect to the daemon).
