### ISSUE TITLE
Action `create_nix_hook_service` errored: failed to fill whole buffer

### ISSUE THREAD

**Issue by VijayakumarRavi** [DeterminateSystems/nix-installer#1280]
## Error
```
Error: 
   0: Planner error
   1: Error executing action
   2: Action `create_nix_hook_service` errored
   3: Io(Error { kind: UnexpectedEof, message: "failed to fill whole buffer" }) (offset 0)
   4: failed to fill whole buffer
```

## Metadata
|key|value|
|--|--|
|**version**|0.27.1|
|**os**|macos|
|**arch**|aarch64|

**Comment by frankhinek** [comment]
Hitting the same error with install `v0.28.0` under macOS 15.1:

```sh
$ curl --proto '=https' --tlsv1.2 -sSf -L https://install.determinate.systems/nix | \
>   sh -s -- install --determinate
info: downloading installer https://install.determinate.systems/nix/tag/v0.28.0/nix-installer-aarch64-darwin
 INFO nix-installer v0.28.0
`nix-installer` needs to run as `root`, attempting to escalate now via `sudo`...
Password:
 INFO nix-installer v0.28.0
Error: 
   0: Planner error
   1: Error executing action
   2: Action `create_group` errored
   3: Group `nixbld` existed but had a different gid (30000) than planned (350)

Location:
   src/cli/subcommand/install.rs:202

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.
```

**Comment by cole-h** [comment]
@frankhinek Your error is not actually the same as this. Yours is because you have an existing Nix installation that created the `nixbld` group with GID 30000, and the version of the nix-installer you're trying to use wants to create it with GID 350. If you don't know how to proceed after this, please open a separate issue and I'd be happy to guide you further.

---

@VijayakumarRavi I've never seen that error before. If you try to install again, do you see the same thing?

**Comment by VijayakumarRavi** [comment]
> @VijayakumarRavi I've never seen that error before. If you try to install again, do you see the same thing?

Yeah, I tried multiple times with different installer versions, but I'm still getting the same error.

**Comment by cole-h** [comment]
@VijayakumarRavi Since it's reproducible to you, would you mind rerunning with `-vvv` and then uploading all the output to https://gist.github.com or something? Thanks! (May be easier if you run the installer binary with `-vvv 2>&1 >/tmp/install-log`.)

I'd also be interested in seeing what `ls -la /Library/LaunchDaemons` and `ls -la /Library/LaunchDaemons/systems.determinate.nix-installer.nix-hook.plist` say.

**Comment by VijayakumarRavi** [comment]
I've run the installer with -vvv as requested and uploaded the log to Gist. I've also included ```ls -la /Library/LaunchDaemons``` output

* [Gist link](https://gist.github.com/VijayakumarRavi/d449b5ec390aa9238ca2ac0063866fbb#file-install-log-md)

**Comment by cole-h** [comment]
Thanks for that! If you remove that empty nix-hook.plist file from there and try again, does that let you proceed further?

**Comment by VijayakumarRavi** [comment]
Thank you so much!! after removing ```nix-hook.plist```, it works fine 🥳
