### ISSUE TITLE
The volume "Nix Store" on disk3s8 couldn't be unmounted because it is in use by process 0 (kernel)

### ISSUE THREAD

**Issue by daneroo** [DeterminateSystems/nix-installer#1303]
## Error
```
Error: 
   0: Error reverting
   0: Action `create_apfs_volume` errored
      Failed to execute command with status 1 `"/usr/sbin/diskutil" "apfs" "deleteVolume" "Nix Store"`, stdout: Started APFS operation
      Deleting APFS Volume from its APFS Container
      Unmounting disk3s8
      The volume "Nix Store" on disk3s8 couldn't be unmounted because it is in use by process 0 (kernel)

      stderr: Error: -69888: Couldn't unmount disk



```

## Metadata
|key|value|
|--|--|
|**version**|0.19.0|
|**os**|macos|
|**arch**|aarch64|

**Comment by cole-h** [comment]
If you reboot, you should be able to rurun and complete the uninstall (there might be lots of errors because we already cleaned up everything before this point, so you can ignore those).

We're looking into ways to make this better, but for now, you should be able to just rerun the uninstall after rebooting and then reinstall at that point.

**Comment by daneroo** [comment]
Thanks for your help and support
We can close this item.

**Comment by daneroo** [comment]
Thanks for your help and support
We can close this item.
