### ISSUE TITLE
macOS version check in installer script is outdated

### ISSUE THREAD

**Issue by harry-xm** [DeterminateSystems/nix-installer#1359]
Before commit 6beefac4d23bd9a0b74b6758f148aa24d6df3ca9, running the installer script on macOS 15 would produce the following error:

```
Warning: Detected unknown macOS major version: 15.2
Warning TLS capabilities detection may fail
```

which came from here and has inconsistent output (missing `:` on one line).

https://github.com/DeterminateSystems/nix-installer/blob/0ba88090bfe30e96abedab58228c8adc326277e2/nix-installer.sh#L381-L388

Is it desirable to make the output consistent and cover newer macOS versions?

**Comment by cole-h** [comment]
> Is it desirable to make the output consistent and cover newer macOS versions?

Not really, mostly because I want to keep the drift between our modification of the script and the rustup-init.sh script we copied as small as possible. Since rustup-init.sh hasn't changed this, and we won't get to this branch with the since-merged fix, I don't think I'll change it until they have.

https://github.com/rust-lang/rustup/blob/dc9d072c34eccbee2d9249daea177b9c4263c5da/rustup-init.sh#L718-L742
