### ISSUE TITLE
macOS: nix-installer plan indicates strange `synthetic.conf` error

### ISSUE THREAD

**Issue by jkachmar** [DeterminateSystems/nix-installer#255]
## Description

After a fresh installation on macOS 13.2.1, attempting to invoke `nix-installer plan` fails with the following error:

```shell
crazy-diamond ~ % /nix/nix-installer plan
Error: 
   0: Planner error
   1: Error executing action
   2: `/etc/synthetic.conf` exists with a different mode (100655) than planned (655), consider removing it with `rm /etc/synthetic.conf`

Location:
   /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/core/src/convert/mod.rs:726
```

### Notes

Invoking with `RUST_BACKTRACE=full` doesn't help much, unfortunately.

<details>

<summary> backtrace </summary>

```shell
  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ BACKTRACE ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
   1: __mh_execute_header<unknown>
      at <unknown source file>:<unknown line>
   2: __mh_execute_header<unknown>
      at <unknown source file>:<unknown line>
   3: __mh_execute_header<unknown>
      at <unknown source file>:<unknown line>
   4: __mh_execute_header<unknown>
      at <unknown source file>:<unknown line>
   5: __mh_execute_header<unknown>
      at <unknown source file>:<unknown line>
   6: __mh_execute_header<unknown>
      at <unknown source file>:<unknown line>
   7: __mh_execute_header<unknown>
      at <unknown source file>:<unknown line>
   8: __mh_execute_header<unknown>
      at <unknown source file>:<unknown line>
   9: __mh_execute_header<unknown>
      at <unknown source file>:<unknown line>
  10: __mh_execute_header<unknown>
      at <unknown source file>:<unknown line>
  11: __mh_execute_header<unknown>
      at <unknown source file>:<unknown line>
```

</details>

**Comment by Hoverbear** [comment]
Ahhh this is a fairly new update I wonder if they changed the permissions... I'll confirm and make an update. Thanks!

**Comment by jab** [comment]
I'm seeing a similar error which suggests there may be a more general bug that is still not fixed:

> 2: `/etc/nix/nix.conf` exists with a different mode (100664) than planned (664), consider removing it with `rm /etc/nix/nix.conf`

Or maybe the error handling just needs to be improved? As a new user, I would like for the installer to either treat the expected 100664 mode the same as the actual 664 mode, or at least offer to remove the file for me and continue, rather than making me remove it myself and re-run (only to potentially find another file with unexpected mode that I have to remove and then start over again).

Hope this helps and thanks for the great work on nix-installer.

**Comment by Hoverbear** [comment]
It may be this change still, we haven't yet cut a release including #259
