### ISSUE TITLE
Fetcher doesn't use system SSL certificates

### ISSUE THREAD

**Issue by piperswe** [DeterminateSystems/nix-installer#300]
We have a MitM TLS proxy at work that requires all TLS clients to allow our corporate root cert. It looks like adding `rustls-tls-native-roots` to `reqwest`'s features _should_ make it look for the system root certs, but it doesn't seem to be working for me (not sure why, it has the same unknown issuer error as if the feature weren't set).

**Comment by Hoverbear** [comment]
Thanks for this report! I'll take a look.

**Comment by Hoverbear** [comment]
I'm wondering if we need to change, instead of add, this feature? Reading the docs it's a bit unclear:

![image](https://user-images.githubusercontent.com/130903/223795961-5c1de1ac-8df9-42af-b7ed-59343933969e.png)

It seems to imply `rusttls-tls` implies `rustls-tls-webpki-roots` which is different than `rustls-tls-native-roots`...

**Comment by Hoverbear** [comment]
Can you try

```
curl --proto '=https' --tlsv1.2 -sSf -L https://install.determinate.systems/nix/pr/332 | sh -s -- install
```
