### ISSUE TITLE
uninstalling with 0.2.0 and installing with 0.5.0 doesn't work. Lingering fstab entry and lingering nixbld groups

### ISSUE THREAD

**Issue by arianvp** [DeterminateSystems/nix-installer#329]
## Error
```
Error: 
   0: Planner error
   1: Error executing action
   2: Child action `create_fstab_entry`
   3: An `/etc/fstab` entry for the `/nix` path already exists, consider removing the entry for `/nix`d from `/etc/fstab`
```

**Comment by arianvp** [comment]
Deleted and now I Get this:

```
arian@Arians-MacBook-Pro nixos-stuff % curl --proto '=https' --tlsv1.2 -sSf -L https://install.determinate.systems/nix | sh -s -- install
info: downloading installer https://install.determinate.systems/nix/tag/v0.5.0/nix-installer-aarch64-darwin
`nix-installer` needs to run as `root`, attempting to escalate now via `sudo`...
Error: 
   0: Planner error
   1: Error executing action
   2: Child action `create_users_and_group`
   3: Group `nixbld` existed but had a different gid (3000) than planned (30000)

Location:
   src/cli/subcommand/install.rs:142

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.

```

**Comment by Hoverbear** [comment]
Hi Arian! I think we spoke about this on a different medium already, but recapping for others:

I am a bit confused why you still had a lingering fstab entry. I recall we did have some bugs around that and changed to use UUIDs in the next version. I'm going to chalk it up to "Strangeness" unless we hear other cases. I believe the problem should be fixed in more recent versions.

Regarding the users, yes, it's quite unfortunate that we changed the gids since then and also don't suggest how you can delete the user. Unfortunately 0.2.0 on Mac could not delete users (We had issues testing it so didn't enable it until just last version), so it left remnants of users on uninstall, this meant they were still present on reinstall with 0.5.0. The correct command to delete users is `sudo dscl . delete /Users/nixbld1`, for example.

Based on our conversation on the other medium, I'm closing this as resolved. Please reopen if that's not the case!
