### ISSUE TITLE
Enabling nix-daemon.socket fails

### ISSUE THREAD

**Issue by clamydo** [DeterminateSystems/nix-installer#363]
I ran `curl --proto '=https' --tlsv1.2 -sSf -L https://install.determinate.systems/nix | sudo sh -s -- install` in WSL 2 (systemd) in Ubunut 22.04.2 LTS and the installer fails to enable the `nix-daemon.socket`.

Shouldn't the command use the symlink in `/etc/systemd/system/nix-daemon.socket`, thus `systemctl enable --now /etc/systemd/systemd/nix-dameon.socket`?

## Error
```
Error: 
   0: Install failure
   1: Error executing action `configure_init_service`
   2: Failed to execute command with status 1 `"systemctl" "enable" "/nix/var/nix/profiles/default/lib/systemd/system/nix-daemon.socket" "--now"`, stdout: 
      stderr: Created symlink /etc/systemd/system/sockets.target.wants/nix-daemon.socket → /nix/var/nix/profiles/default/lib/systemd/system/nix-daemon.socket.
      Job for nix-daemon.socket canceled.


```

**Comment by Hoverbear** [comment]
I wish it was a mistake. :sweat:

Right now we do this because some older distros (Like Ubuntu 16.04) would report errors if we used the one in `/etc/systemd/system/nix-daemon.socket` about "Too many levels of symlinks".

In theory this should not present you with an issue, could you run `journalctl -u nix-daemon.socket` and maybe we can find out why it was cancelled?

**Comment by Hoverbear** [comment]
That is very odd... We do have a test script that we run on Windows which I just checked is still working

https://github.com/DeterminateSystems/nix-installer/blob/11834a3aabb74ece09257d4ac7612d79f6f27661/tests/windows/test-wsl.ps1#L39

Those tests are on Jammy (22.04) even.

I wonder what is happening... You said your `journalctl -u nix-daemon.socket` is empty? What about checking the very newest entries of `journalctl -xe` after an attempt?

**Comment by clamydo** [comment]
I've tested it with a new WSL2 instance (Ubuntu 22.04 from Windows Store) and it works without issue.

Not sure what is broken, with the other instance. However, it is rather old and I've upgrade Ubuntu manually.

> I wonder what is happening... You said your journalctl -u nix-daemon.socket is empty? What about checking the very newest entries of journalctl -xe after an attempt?

Yes it is empty and so is journalctl after an attempt 🤷 

I'm closing, will be probably hard to reproduce for somebody else.

**Comment by Hoverbear** [comment]
Thanks for reporting anyways @clamydo :)

**Comment by Hoverbear** [comment]
Thanks for reporting anyways @clamydo :)

**Comment by timblaktu** [comment]
Sorry for the necro, but I'm getting this same issue when trying to install the multi-user nix with `sh <(curl -L https://nixos.org/nix/install) --daemon` on a systemd-enabled Debian 12 running in wsl2. Note this does NOT happen in my Ubuntu 22.04.3 WSL2 machine, ONLY on the Debian 12 one...

I have reproduced this twice on this system, following the [multi-user uninstall instructions](https://nixos.org/manual/nix/unstable/installation/uninstall.html#linux) in-between. Here is the output I got both times:

```
.
.
.
I am executing:

    $ sudo systemctl enable /nix/var/nix/profiles/default/lib/systemd/system/nix-daemon.socket

to set up the nix-daemon socket service


---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo systemctl daemon-reload

to load the systemd unit for nix-daemon


---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo systemctl start nix-daemon.socket

to start the nix-daemon.socket

Job for nix-daemon.socket canceled.

---- oh no! --------------------------------------------------------------------
Oh no, something went wrong. If you can take all the output and open
an issue, we'd love to fix the problem so nobody else has this issue.

:(

We'd love to help if you need it.

You can open an issue at
https://github.com/NixOS/nix/issues/new?labels=installer&template=installer.md

Or get in touch with the community: https://nixos.org/community
```

Each time, the install exits 1 and I subsequently see nothing in `journalctl -u nix-daemon.socket` nor `journalctl -u nix-daemon.service`.

The systemd units seem to exist and be enabled:

```
> sudo systemctl list-unit-files | grep nix                                                                                                                  ~  % (⎈|BINARY-N/A:N/A)
nix-daemon.service                     linked          enabled
nix-daemon.socket                      enabled         enabled
```

Searching `nix-daemon` in `journalctl -xe`, I see that every time the service or socket is told to start, the same systemd error is logged:

```
May 16 09:17:19 sector17g-debian systemd[1]: proc-sys-fs-binfmt_misc.automount: Path /proc/sys/fs/binfmt_misc is already a mount point, refusing start.
May 16 09:17:19 sector17g-debian systemd[1]: Failed to set up automount proc-sys-fs-binfmt_misc.automount - Arbitrary Executable File Formats File System Automount Point.
```

Going down this rabbit hole, it is not clear if this error is caused by wsl or systemd bug. This is my windows version:

Edition	Windows 11 Home
Version	23H2
Installed on	‎2/‎20/‎2024
OS build	22631.3593
Experience	Windows Feature Experience Pack 1000.22700.1003.0

and my WSL version is:

WSL version: 2.1.5.0
Kernel version: 5.15.146.1-2
WSLg version: 1.0.60
MSRDC version: 1.2.5105
Direct3D version: 1.611.1-81528511
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.22631.3593

**Comment by cole-h** [comment]
This repository is for our nix-installer, not the upstream one. You may have better luck reporting your issue there: https://github.com/NixOS/nix/issues

**Comment by grahamc** [comment]
(but you might want to try ours:

```
 curl --proto '=https' --tlsv1.2 -sSf -L \
  https://install.determinate.systems/nix | sh -s -- install
```

:)

)

**Comment by timblaktu** [comment]
@grahamc running the DeterminateSystems/nix-intaller on the same Debian system I reported above (which had failed with the upstream installer), also failed somewhere in the `Configure Nix daemon related settings with systemd` step. Since it didn't give much info about what went wrong, I reverted, and re-ran the install command with `RUST_BACKTRACE=full`, and this produced an empty backtrace but the other output suggests that nix-installer failed exactly the same way the upstream one did, so it's probably something with this particular machine:

```
> export RUST_BACKTRACE=full; curl --proto '=https' --tlsv1.2 -sSf -L https://install.determinate.systems/nix | sh -s -- install
info: downloading installer https://install.determinate.systems/nix/tag/v0.19.0/nix-installer-x86_64-linux
`nix-installer` needs to run as `root`, attempting to escalate now via `sudo`...
Nix install plan (v0.19.0)
Planner: linux (with default settings)

Planned actions:
* Create directory `/nix`
* Extract the bundled Nix (originally from /nix/store/k51vv8b59cbjgf61l1klx6lqsa8mb0s1-nix-binary-tarball-2.21.2/nix-2.21.2-x86_64-linux.tar.xz)
* Create a directory tree in `/nix`
* Move the downloaded Nix into `/nix`
* Create build users (UID 30001-30032) and group (GID 30000)
* Setup the default Nix profile
* Place the Nix configuration in `/etc/nix/nix.conf`
* Configure the shell profiles
* Create directory `/etc/tmpfiles.d`
* Configure Nix daemon related settings with systemd
* Remove directory `/nix/temp-install-dir`


Proceed? ([Y]es/[n]o/[e]xplain): Y
 INFO Step: Create directory `/nix`
 INFO Step: Provision Nix
 INFO Step: Create build users (UID 30001-30032) and group (GID 30000)
 INFO Step: Configure Nix
 INFO Step: Create directory `/etc/tmpfiles.d`
 INFO Step: Configure Nix daemon related settings with systemd
ERROR
   0: Install failure
   1: Error executing action
   2: Action `configure_init_service` errored
   3: Failed to execute command with status 1 `"systemctl" "enable" "/nix/var/nix/profiles/default/lib/systemd/system/nix-daemon.socket" "--now"`, stdout:
      stderr: Created symlink /etc/systemd/system/sockets.target.wants/nix-daemon.socket → /nix/var/nix/profiles/default/lib/systemd/system/nix-daemon.socket.
      Job for nix-daemon.socket canceled.

   3:

Location:
   src/cli/subcommand/install.rs:250

  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ BACKTRACE ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  <empty backtrace>
```
