### ISSUE TITLE
`/usr/share/fish/` not writable on Steam Deck

### ISSUE THREAD

**Issue by jupblb** [DeterminateSystems/nix-installer#367]
The process failed when installing on a fresh Steam Deck (with SteamOS). Uninstallation proceeded without errors.

## Installation command

``` console
curl --proto '=https' --tlsv1.2 -sSf -L https://install.determinate.systems/nix | sh -s -- install steam-deck
```

## Error
```
Error: 
   0: Install failure
   1: Error executing action `configure_nix`
   2: Child action `configure_shell_profile`
   3: Child action `create_or_insert_into_file`
   4: Open path `/usr/share/fish/vendor_conf.d/nix-installer-tmp.2308479259`
   5: Read-only file system (os error 30)
```

**Comment by detuur** [comment]
This is because the installer is trying to write to a file that is on the read-only partition on the Steam Deck. Doing `steamos-readonly disable` beforehand doesn't work because the partition gets set to read-write and read-only again earlier in the install process.

I've found a workaround though. If you prepare `steamos-readonly disable` in a separate terminal, and run it after you see the message `INFO Step: Provision Nix` in the installer, you can re-disable the readonly in time for the file write to go through and the installer to succeed.

**Comment by Hoverbear** [comment]
Thanks for the report! Seems we need to avoid manipulating that profile directory on SteamOS.

**Comment by jupblb** [comment]
I can confirm the installer works now. Thank you! :tada:
