### ISSUE TITLE
Is the APFS volume encrypted or not?

### ISSUE THREAD

**Issue by hydrajump** [DeterminateSystems/nix-installer#422]
I'm on an Apple Silicon Mac running Ventura and FileVault is enabled. When I look at the plan generated by `nix-installer` v0.8.0 it's unclear whether the APFS volume that will be created is encrypted to not.

```
Nix install plan (v0.8.0)
Planner: macos (with default settings)

Planned actions:
* Create an encrypted APFS volume `Nix Store` for Nix on `disk3` and add it to `/etc/fstab` mounting on `/nix`
[...SNIP...]


Proceed? ([Y]es/[n]o/[e]xplain): e
Nix install plan (v0.8.0)
Planner: macos

Configured settings:
[...SNIP...]

* volume_encrypt: null
* volume_label: "Nix Store"
```

`volume_encrypt` seems to indicate no encryption. Should I invoke the installer with `--encrypt true`?

**Comment by Hoverbear** [comment]
Hi! I believe you may have found a bug with our recent version. We should automatically detect if encryption is needed, but that seems to no be working. 

Could you please tell me which version of OS X you are on and the output of these:

```bash
fdesetup status
echo $?
```

For now please pass `--encrypt true`.

**Comment by Hoverbear** [comment]
@hydrajump do you think you could run `fdesetup isactive` for me? I haven't figured out why this is failing yet...

**Comment by Hoverbear** [comment]
I've concluded that the volume detection seems to be working alright. I tested both with FDE on and off and it seems to be working ok.

The reason `volume_encrypt: null` is printing as `null` is because you are not passing a force on/off for encryption. This means during plan-time the planner heuristically detects if it needs to use encryption.

Further evidence supporting that encryption is indeed enabled on your system is that it says `Encrypted` in the planned actions and it would only say that if the action is getting `encrypt` set:

https://github.com/DeterminateSystems/nix-installer/blob/79a32a7c668af6936f272960dbab80b05019bd16/src/action/macos/create_nix_volume.rs#L130-L131
