### ISSUE TITLE
keychain lacks password for existing Nix Store

### ISSUE THREAD

**Issue by Stevengre** [DeterminateSystems/nix-installer#433]
## Error
```
Error: 
   0: Planner error
   1: Error executing action
   2: Action `encrypt_apfs_volume` errored
   3: The keychain lacks a password for the already existing "Nix Store" volume on disk `disk3`, consider removing the volume with `diskutil apfs deleteVolume "Nix Store"` (if you receive error -69888, you may need to run `launchctl bootout system/org.nixos.darwin-store` and `launchctl bootout system/org.nixos.nix-daemon` first)
```

## Metadata
|key|value|
|--|--|
|**version**|0.8.0|
|**os**|macos|
|**arch**|aarch64|

I got this error after I install Miniconda

**Comment by Hoverbear** [comment]
It looks like you already had a Nix install from previously and the installer detected it couldn't find a key to access it.

Did you follow the suggested resolution in the message? Did it work for you?

**Comment by Stevengre** [comment]
Yes, the suggested resolution does work for me. Thank you.

**Comment by Hoverbear** [comment]
I'd like to better understand what you're wanting to do with `nix-installer plan` beyond messing around! It's mostly a development-focused subcommand that is more a consequence of our design than a command with a well thought out use case. 

The `nix-installer` at the moment is a binary around a `nix-installer` library which has an API that looks something like this:

```rust
use std::error::Error;
use nix_installer::InstallPlan;

let mut plan = InstallPlan::default().await?;
match plan.install(None).await {
    Ok(()) => tracing::info!("Done"),
    Err(e) => {
        match e.source() {
            Some(source) => tracing::error!("{e}: {}", source),
            None => tracing::error!("{e}"),
        };
        plan.uninstall(None).await?;
    },
};
```

So the `nix-installer plan` command basically just skips that `.install()` call and produces a json of what it would do, which we could inspect or analyze. The plan phase does all of our pre-install checking since once a plan is produced, it's expected to be able to `plan.install` on that same machine at that same point in time without interaction, and hopefully without error. 

In your case, the plan phase is checking that a keychain password has a spot for the key it would make. Particularly, this APFS volume creation dance is extremely fragile as Apple does not provide good APIs for working with APFS or the keychain, so we can only really manage a "Best-effort".

**Comment by therealpxc** [comment]
At the time, I just wanted to quickly check the syntax of a `nix-installer install` command that I was writing for some documentation (specifically whether `--extra-conf` required repetition for additional extra configuration).

**Comment by Hoverbear** [comment]
`--extra-conf` should be able to take multiline strings, or accept multiple `--extra-conf` args with single strings!

**Comment by Hoverbear** [comment]
(Think this is closable, let me know if otherwise!)
