### ISSUE TITLE
set TasksMax=infinity in nix-daemon systemd unit 

### ISSUE THREAD

**Issue by jcumming** [DeterminateSystems/nix-installer#493]
Hello!

We recently ran across https://github.com/NixOS/nix/issues/3717 during an install to SLES 12SP5. 

Manually adding 

```
TasksMax=infinity
```

to the `nix-daemon` systemd unit file seems to have worked around the problem.

**Comment by Hoverbear** [comment]
Interesting! Thanks for this report. I wonder if infinity is the right setting or we should use something larger than default, but not quite that large...

**Comment by Hoverbear** [comment]
I believe setting this would be the responsibility of Nix.

Our Linux planners directly provision the output artifact of https://github.com/NixOS/nix/blob/master/misc/systemd/nix-daemon.service.in#L12 without modifications, so changing that file in the `nix` project would be the best way to make this change.

I've followed up on the Nix issue with a PR to Nix.

Because of this, I'm going to close this issue!

**Comment by Hoverbear** [comment]
This was merged upstream! https://github.com/NixOS/nix/pull/8660
