### ISSUE TITLE
Disable installing `nix-*` family of commands

### ISSUE THREAD

**Issue by srid** [DeterminateSystems/nix-installer#498]
Since this installer is flake-first would it be good idea to at least make it an option to disable the presence of `nix-*` family of commands in path?

**Comment by Hoverbear** [comment]
This would only really be possible if we installed a different `nix` artifact, which would likely cause a large number of technical problems for users (since we'd basically have to override their nix package).

Beyond that, I don't think our users would appreciate this. Some folks want and need these commands, and taking
