### ISSUE TITLE
Default planner downloads old installer version

### ISSUE THREAD

**Issue by beijn** [DeterminateSystems/nix-installer#529]
The default installation command from the [`README.md`](https://github.com/DeterminateSystems/nix-installer/blob/main/README.md#the-determinate-nix-installer) downloads the outdated version `v0.8.0` of the installer and not the current one (`v0.9.1`).
```sh
❯ curl --proto '=https' --tlsv1.2 -sSf -L https://install.determinate.systems/nix | sh -s -- install

info: downloading installer (https://install.determinate.systems/nix/tag/v0.8.0/nix-installer-x86_64-linux)
```
(The new installer works perfectly :heavy_check_mark:, but the old version does not work on my system due to not creating or not properly removing the systemd files).

**workaround**:  curl from the newest release link `curl --proto '=https' --tlsv1.2 -sSf -L https://github.com/DeterminateSystems/nix-installer/releases/download/v0.9.1/nix-installer.sh | sh -s -- install`

**Comment by Hoverbear** [comment]
With 0.9.1 we were experimenting with a new feature so did a limited rollout, it's a good thing too since we met some bugs with `auto-uid-allocation` on mac. We're going to release a new 0.10.0 this week and pretty aggressively roll that out with Nix 2.15! In the meantime you should be able to do `nix upgrade-nix` to update.

**Comment by Hoverbear** [comment]
0.10.0 is fully rolled out now!
