### ISSUE TITLE
Install Linux planner into home directory?

### ISSUE THREAD

**Issue by jaidetree** [DeterminateSystems/nix-installer#538]
Exploring using Nix with a remote development container service. In short, the $HOME directory persists across shutdowns, but everything else in the VM will be reset. I was curious how one would use this to install nix into $HOME/nix instead of /nix as it seems to be hardcoded default in the Linux planner.

Is there something I'm missing?

**Comment by Hoverbear** [comment]
I want something like this too! Unfortunately, `nix` itself requires things to be rooted at `/nix` since the binaries from the cache will are dylinked to paths in `/nix/store`. :( There is some tinkering you could probably do.

I think best the way to do this would be to create a systemd mount unit that bind mounts some folder in the `$HOME` onto `/nix`, however you'll also need to use `systemd-tmpfiles` to create that `/nix` path.

This strategy would be rather similar to our `steam-deck` planner. (Though, SteamOS now does this for us!)

The mount unit would look similar to this:

```ini
# /etc/systemd/system/nix.mount
[Unit]
Description=Mount `/home/my-user/nix` on `/nix`
PropagatesStopTo=nix-daemon.service
PropagatesStopTo=nix-directory.service
After=nix-directory.service
Requires=nix-directory.service
ConditionPathIsDirectory=/nix
DefaultDependencies=no

[Mount]
What=/home/my-user/nix
Where=/nix
Type=none
DirectoryMode=0755
Options=bind

[Install]
RequiredBy=nix-daemon.service
RequiredBy=nix-daemon.socket
```

The [systemd-tmpfiles](https://www.freedesktop.org/software/systemd/man/tmpfiles.d.html#) would be like this (it may also need to be turned on for your system!): 

```
# /etc/tmpfiles.d/nix.conf
d /nix
```

If you do attempt this, we found that if systemd starts *before* the mount is done it won't detect the units which the nix-installer links into your system from `/nix`, so you need a unit kinda like this which will prompt the daemon to reload the linked units.

```ini
# /etc/systemd/system/ensure-symlinked-units-resolve.service
[Unit]
Description=Ensure Nix related units which are symlinked resolve
After=nix.mount
Requires=nix.mount
DefaultDependencies=no

[Service]
Type=oneshot
RemainAfterExit=yes
ExecStart=/usr/bin/systemctl daemon-reload
ExecStart=/usr/bin/systemctl restart --no-block nix-daemon.socket

[Install]
WantedBy=sysinit.target
```

If you started the `nix.mount` unit that should create a `/nix`, if that's done the `nix-installer` *should* work.

**Comment by jaidetree** [comment]
@Hoverbear Thanks for the detailed explanation! That said, I am working in a linux container without systemd. Does that significantly change your solution?

I do have the ability to customize the container and modify the Dockerfile. So maybe a bindmount could be created there?


https://github.com/jaidetree/build-hacker-tools

**Comment by Hoverbear** [comment]
Yup doing it with `/etc/fstab` or whatever should work fine then. :)

**Comment by Hoverbear** [comment]
Closing this as I think you've found a workaround. If not please reopen and we can see if something else will work.
