### ISSUE TITLE
The installer should work on nixos too (for enabling nix-command and setting up flakes for nixos)

### ISSUE THREAD

**Issue by dnkmmr69420** [DeterminateSystems/nix-installer#609]
You might be thinking "nixos already has nix" but that is true but nixos doesn't come with flakes enabled and other things out of the box. So I was thinking that this installer should be able to modify the configuration.nix file by doing the following

- enable flakes
- enable nix-command
- set up flakes for configuration.nix
- enable auto-optimise the store
- Install NVIDIA if the system uses NVIDIA

**Comment by Hoverbear** [comment]
NixOS is a very different beast than Nix and I do not consider performing otherwise trivial edits to your NixOS config to be of particular use. Perhaps the installer should provide the user with some guiance on how to modify their NixOS config, but there is a lot of complexity in how people set up their configs that it's a big can of worms. (For example, my nixos systems are built from a flake in a remote repo, the installer would not be able to update it.)

Such an implementation doing things like installing NVIDIA support is most certainly outside the scope of this installer.
