### ISSUE TITLE
[macOS] prevent the creating of /nix?

### ISSUE THREAD

**Issue by angerman** [DeterminateSystems/nix-installer#610]
I have an external disk that holds /nix; and I'm happy to ensure that /nix is properly mounted (and has the synthetic.conf entry). Can I somehow sidestep the volume creation on macOS? I don't need the installer to create an APFS volume, ... It's there, I just need it to use it.

Happy to look into this as well, if someone could give me some rough guidance.

**Comment by Hoverbear** [comment]
Unfortunately the dance of creating a Nix volume is annoyingly complicated as there are many states which the user system may be in which look fine but are otherwise broken. There has been some effort made to support this situation, however it's quite difficult and labor-intensive for me to test accurately as I don't use a Mac and our test Macs don't have external disks.

If you're interested, there is a `create_nix_volume.rs` inside `src/actions/macos` which composes together several other actions that make up the volume logic. Each of those actions has a `plan` function where we try to detect if the step is already completed.

If you run `nix-installer plan > plan.json` then review the `plan.json` the first entry in `actions` should be the volume creation stuff. You can see that some of those plan steps will be `state: "Completed"`, those it's properly detecting are already done, however something to do with the volume creation is `state: "Uncompleted"`. If you could figure out which one, we could possibly fix the issue.

As a hack/workaround, you can likely change the `state` of that first `actions` entry to `Completed` then run `nix-installer install --plan plan.json` and entirely skip volume creation.

There may also be issues around the launchd services we have to provision, as those are relatively tightly bound to the volumes we create, so we may not be out of the woods after this fix.

**Comment by angerman** [comment]
Just wanted to leave this here. It appears (after reading the code, and thinking it might work), this actually does work:
```
# install
curl --proto '=https' --tlsv1.2 -sSf -L https://install.determinate.systems/nix \
  -o /var/root/nix-installer
chmod +x /var/root/nix-installer
/var/root/nix-installer install macos \
  --volume-label "Nix Store" \
  --root-disk $(diskutil list |grep "Nix Store"|egrep -o '(disk\d+)') \
  --no-confirm
  ```
Using the `--volume-label` and `--root-disk` options combined on a on an _unmounted_ apfs disk seems to have the desire effect.
