### ISSUE TITLE
home-manager does not work out of the box

### ISSUE THREAD

**Issue by shyim** [DeterminateSystems/nix-installer#628]
In WSL (Debian). I installed nix using this installer and wanted to setup now home-manager but it fails with:

```
Could not find suitable profile directory, tried /home/shyim/.local/state/home-manager/profiles and /nix/var/nix/profiles/per-user/shyim
```

Simple `mkdir -p ~/.local/state/nix/profiles` solved it for me. (Found on reddit https://www.reddit.com/r/Nix/comments/1443k3o/home_manager_installation_could_not_find_suitable/jr9ht5g/)

I guess the installer should create that folder.

**Comment by bestlem** [comment]
See https://github.com/DeterminateSystems/nix-installer/issues/350#issuecomment-1712101904 where @hoverbear suggests that the installer won't deal with home-manager (and nix-darwin) specifics.

**Comment by shyim** [comment]
hmm. than the installer is not ideal for me at least. The second path seems "default" in nix https://nixos.wiki/wiki/User_Environment

**Comment by Hoverbear** [comment]
@bestlem I'd prefer you did not take my words out of context. In that issue we were discussing having the installer automatically install nix-darwin and/or home-manager. This is a bug report where the user was surprised while trying to install `home-manager` after using the installer.

**Comment by Hoverbear** [comment]
@shyim I was able to reproduce your issue!

* Installed Debian from the Microsoft Store
* Ran initial setup on Debian.
* Ran `sudo apt install curl`
* Wrote the systemd setting to the `wsl.conf` as so: https://ubuntu.com/blog/ubuntu-wsl-enable-systemd, making sure to shut down and restart the wsl distrow
* Ran `curl --proto '=https' --tlsv1.2 -sSf -L https://install.determinate.systems/nix | sh -s -- install`
* Followed the instruction of running `. /nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh`
* Proceeded to follow the Home Manager Standalone flakes setup: https://nix-community.github.io/home-manager/index.html#sec-flakes-standalone, running `nix run home-manager/master -- init --switch`.

I suspect what is happening here the same as https://github.com/nix-community/home-manager/issues/4403. It is likely best to look forward to an upstream fix in `home-manager` as the isuee is active and some people are assigned. I am confident in their abilities to fix it. :)

In... I believe Nix 2.15? (I don't see it in the changelog, but we dealt with issues related) ... The default profile location was changed. You can see the documentation here: https://nixos.org/manual/nix/stable/command-ref/new-cli/nix3-profile#profiles. Similar documentation from an old version in Ubuntu shows this to be a different location back then: https://manpages.ubuntu.com/manpages/jammy/man1/nix3-profile.1.html

So, `/nix/var/nix/profiles/per-user/shyim` is not where a profile goes anymore.

`$NIX_STATE_DIR/profiles/per-user/root` is now only used for `root`, otherwise the profile directory is under `$XDG_STATE_HOME/nix/profiles`.

**Comment by e-nikolov** [comment]
Should be fixed by https://github.com/nix-community/home-manager/commit/ae896c810f501bf0c3a2fd7fc2de094dd0addf01

**Comment by Hoverbear** [comment]
Nice! Thank you!
