### ISSUE TITLE
[Bug] When install script fails, it should exit with non-0 error code

### ISSUE THREAD

**Issue by kkimdev** [DeterminateSystems/nix-installer#653]
Our use case is that the Nix install script is a part of a larger install procedure, and the install process should be halted when a sub-step fails.  Currently, it seems there is no way to detect the Nix install script fails since it returns 0 error code (success) even when it fails.

```
 $ ./nix-installer install
`nix-installer` needs to run as `root`, attempting to escalate now via `sudo`...
Found existing plan in `/nix/receipt.json`, with the same settings, already completed, try uninstalling (`/nix/nix-installer uninstall`) and reinstalling if Nix isn't working
```

**Comment by Hoverbear** [comment]
In this particular error case, exiting 0 is intended. That's because as far as the installer can tell, the task is already complete and `nix` should be working. This is the mechanism the GH action uses to avoid attempting to reinstall where appropriate. 

We should provide users with a way to avoid this behavior though...

Also looking at these snippets it's clear there is some inconsistency which should be fixed.

https://github.com/DeterminateSystems/nix-installer/blob/d01e1b820cd3394c181f741e0bd4d3a5112c88b2/src/cli/subcommand/install.rs#L131-L132 
https://github.com/DeterminateSystems/nix-installer/blob/d01e1b820cd3394c181f741e0bd4d3a5112c88b2/src/cli/subcommand/install.rs#L183-L184

**Comment by kkimdev** [comment]
@Hoverbear Thanks for the comment and the investigation!

We would like to make our project's install script as idempotent as possible.  Also, one important use case is fixing any dev issues by simply reinstalling everything.  Our script doesn't have to be perfectly idempotent, but it will be great at least if we can tell users that Nix needs to be uninstalled first for a clean reinstall.

So we just want to know if `nix-installer` will fail because it's already installed, and doesn't necessarily have to be the exit code.  Maybe we should just check the existence of `/nix/receipt.json`?

**Comment by kkimdev** [comment]
Or how about `nix-installer` flag something like `--reinstall-if-installed`?

**Comment by Hoverbear** [comment]
Something like that, or like a `refresh` subcommand which would combine uninstall and install if needed... Hmm...

**Comment by Hoverbear** [comment]
@kkimdev Yeah I would check for `/nix/receipt.json` for now, until we have something better!
