### ISSUE TITLE
Compatible with Nushell

### ISSUE THREAD

**Issue by dougg0k** [DeterminateSystems/nix-installer#894]
Hi,

Anything that can be done to make it work with nushell?

Currently, only `sh/bash` seems to be supported on that part.

---

Its probably incorrect to do so, but, I have set `NIX_INSTALLER_BINARY_ROOT` to `/nix` and added the variable to the path. It seems to at least recognize the  executable.

---

But then I get this

```
nu ✗ nix-installer --version
nix-installer 0.17.1

nu ❯ nix-installer self-test
 INFO Successfully tested Nix install in all discovered shells. shells=["sh", "bash"]
                                                                                                                                                                                               
~ as 🧙 took 2s
nu ❯ nix-installer plan
`nix-installer` needs to run as `root`, attempting to escalate now via `sudo`...
env: ‘nix-installer’: No such file or directory

~ as 🧙 took 2s
nu ✗ nix-installer repair
`nix-installer` needs to run as `root`, attempting to escalate now via `sudo`...
env: ‘nix-installer’: No such file or directory

~ as 🧙
nu ✗ nix-installer install
`nix-installer` needs to run as `root`, attempting to escalate now via `sudo`...
env: ‘nix-installer’: No such file or directory
```

**Comment by cole-h** [comment]
(We support `fish` and `zsh` too.)

The first step would be to get nushell supported upstream in Nix, since we don't maintain the profile scripts that setup e.g. the PATH and related environment variables necessary for Nix to function properly: https://github.com/NixOS/nix/blob/7d2ead50e5ee6223f2ca3e5c80695f209ae4eb9a/scripts/nix-profile-daemon.sh.in, https://github.com/NixOS/nix/blob/7d2ead50e5ee6223f2ca3e5c80695f209ae4eb9a/scripts/nix-profile-daemon.fish.in

**Comment by dougg0k** [comment]
Right. There seem to be an issue already open for that. https://github.com/NixOS/nix/issues/9813
