### ISSUE TITLE
Auto get latest version

### ISSUE THREAD

**Issue by dougg0k** [DeterminateSystems/nix-installer#895]
Hi,

Why this https://github.com/DeterminateSystems/nix-installer/blob/main/src/settings.rs#L15 isn't fetching the latest version automatically?

https://api.github.com/repos/NixOS/nix/tags - Get first item (name) on the array.

`curl https://api.github.com/repos/NixOS/nix/tags -s | jq .[0].name -r`

**Comment by cole-h** [comment]
We don't automatically use the latest version for (at least) a couple of reasons:

1. Sometimes a new Nix release has issues that aren't noticed until people start trying it out (either in CI or a new install on some machine)
2. By specifying an exact version of Nix in every release of our installer, we don't have to chase down issues like "this new version of Nix does something different that we haven't accounted for yet" -- we'll notice when we bump the default version when preparing for a release (or if some adventurous user decides to manually specify a newer version), but it won't otherwise affect users before we're ready for it to.


(There may be more reasons, but these are the ones that immediately come to mind)

---

There's nothing stopping you from hacking this in yourself, though -- we support the `--nix-package-url` argument to the `install` subcommand.
