### ISSUE TITLE
Uninstall not possible

### ISSUE THREAD

**Issue by ShalokShalom** [DeterminateSystems/nix-installer#952]
I just tried to uninstall Nix, and encountered the following issue. 

Is there anything else, I can provide?
non-NixOS

## Error
```
Error: 
   0: Reading receipt
   1: No such file or directory (os error 2)
```

## Metadata
|key|value|
|--|--|
|**version**|0.18.0|
|**os**|linux|
|**arch**|x86_64|

**Comment by cole-h** [comment]
Hm, that's very strange. Did you do anything before trying to uninstall that would have lead to the receipt being deleted?

You should be able to rerun the installer (which will "repair" itself and create a new receipt), and then uninstall with that new receipt.

**Comment by ShalokShalom** [comment]
I did uninstall by following the manual way from the official documentation. 
Guess I can close this?

**Comment by cole-h** [comment]
Glad you got it solved! With our installer, it's preferable to uninstall using `/nix/nix-installer uninstall`, as that will do all of the necessary cleanup for you. The official installer doesn't offer something like that and has to resort to manual steps because it doesn't create a kind of receipt like we do.

If that somehow doesn't clean everything up, feel free to open an issue about it!

**Comment by ShalokShalom** [comment]
Yeah, I tried doing that. This is the exact command, that lead to this issue report. 
Thanks a ton for you assistance, greatly appreciated.
